### ISSUE TITLE
Errors in command function description

### ISSUE THREAD

**Issue by thefrogline** [Simplix-Softworks/PunishControl-Wiki#1]
**Describe the bug**
I see that there are several errors in the description of the functionality of the commands, for example the command / unban, it says that it is to ban someone

**Screenshots**
![image](https://user-images.githubusercontent.com/76601496/120516933-83942680-c395-11eb-85f2-0d5213073b2d.png)
![image](https://user-images.githubusercontent.com/76601496/120517648-49775480-c396-11eb-9856-fdb682993dda.png)

**Platform**
- Which platform are you on: Spigot
- Are you using a fork Paper
- Which version is your server on 1.16.5
- Are there any other plugins that might be interfering? 

**To Reproduce**
If applicable:
1. Go to '..

**Comment by KotlinFactory** [comment]
Thank you so much for reporting this. We changed this :)
