### ISSUE TITLE
Webinterface suggestion: Punishments.

### ISSUE THREAD

**Issue by PersonalDom** [Simplix-Softworks/PunishControl-Wiki#2]
I suggest allowing users to add punishments (Mute/warn/kick/ban) through the web interface, wherever they are in the world. This would be a useful and highly respectable feature for the web panel, as currently it can only _show_ punishments.

**Comment by KotlinFactory** [comment]
Hey PersonalDom,

thank you so much for suggesting this.
We plan to implement this once PunishControl is more mature.

Regards,
Leonhard

**Comment by alexander-zierhut** [comment]
This is possible, but I dread the thought of the support problems people will have when installing and making an endpoint available.

**Comment by PersonalDom** [comment]
> This is possible, but I dread the thought of the support problems people will have when installing and making an endpoint available.

What do you mean? 

Couldn't you just add the appropriate database record and then post the update to the server?

**Comment by KotlinFactory** [comment]
Won't be able to do this at the moment
