### ISSUE TITLE
Add more details to auto punisher and ability to view player punish menu quicker

### ISSUE THREAD

**Issue by MythricHD** [Simplix-Softworks/PunishControl-Wiki#3]
**1)**
I noticed that right now it's a bit hard to tell what the autopunish is going to output just based on the limited lore info. It would be nice if it was formatted more like the template where it tells you info about what punishment will be given and how long.

Here is a screenshot to reference:
![5MJtDzP6Yt](https://user-images.githubusercontent.com/70623476/130363002-173ccded-548b-4b12-8168-2ada90e4bd68.png)

**2)**
It would also be nice if we could add custom lores to an autopunishment to give staff a bit of info on what the punishment relates to. This is what I used for a previous punishment menu: https://i.riftmc.co/sWzjrQIzzq.png It would be important to have unique lores for each auto punishment to give detail on what that punishment does. Could look something like this in the autopunish lore https://paste.helpch.at/ufojadoted.bash to show the custom info before the punish stats.

**3)**
https://i.riftmc.co/bkheLubezz.png It would be nice to have a command that directly links to the punish player menu right now you have to go through the player list but having a command like `/punish <ign>` to directly open the menu would make it simpler for staff

**4)**
Addition of two placeholders to autopunish lore https://paste.helpch.at/nesihasara.bash

{autopun_current_puns} Shows how many offenses of an autopunish a player has already had. In the config it could show something like 3/5 meaning they have been autopunished 3 times out of the total 5 punishments.

{autopun_expiration} Shows the value of time-off-set set in the config. This can be used by staff to tell how long ago they received their previous auto punishment. Would be a nice visual to have

**Comment by KotlinFactory** [comment]
Hey, 
thank you for your ideas. We are looking forward to be implementing them soon.

Regards,
 Leonhard

**Comment by KotlinFactory** [comment]
1) Is now implemented with 2.1.3

**Comment by KotlinFactory** [comment]
2) Is Implemented with 2.1.4 However the placeholder is called autopun_time_off_set
3) Is already implemented using /banall /muteall /warnall
4) Current punishments can not really be implemented since this would cause a lot of lag. The final duration is calculated once the player is auto punished.

**Comment by KotlinFactory** [comment]
All implemented :)
