### ISSUE TITLE
Web Panel Not Fully Functional

### ISSUE THREAD

**Issue by MythricHD** [Simplix-Softworks/PunishControl-Wiki#4]
**Describe the bug**
Opening per requested previously had discord DMS. https://i.riftmc.co/HJobmgWSnV.png

**Screenshots**
https://i.riftmc.co/OBuCcwpnEQ.png This is the home page, does not look proper according to alex
https://i.riftmc.co/m7PDfYSdWL.png This is the lookup page, it does not show the players properly.

**Platform**
- Which platform are you on: Bungee
- Which version is your server on 1.16.5
- Plugin version: 2.2.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browswer: Chrome
 - Java-Version: 1.16.0

**Comment by MythricHD** [comment]
XAMPP Control Panel: https://i.riftmc.co/fPBWxkjMMf.png

**Comment by KotlinFactory** [comment]
Hey,
thank you so much for reporting this.

We will have a look at this.

Regards,
Leonhard

**Comment by KotlinFactory** [comment]
Resolved in DM

**Comment by KotlinFactory** [comment]
Please comment if otherwise
