### ISSUE TITLE
No more Custom Recipes Bug

### ISSUE THREAD

**Issue by Effendil** [Simplix-Softworks/PunishControl-Wiki#6]
**Describe the bug**
If i put in this Plugin all Custom Recipes regardless from where there are get deleted. No Custom Recipes on my Server if
this Plugin is installed... very weird.

**Platform**
- Spigot
- 1.17.1
- Tested on Paper/Airplane and LightSpigot
- All Plugins that bring Recipes in

**Desktop (please complete the following information):**
 - Ubuntu
 - Version 20.04.3 LTS
 - Java-Version: OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

**Files**
- debug.log is empty, nothing to show

**To Reproduce**
Drag and Drop the Plugin into your plugin-folder

**Comment by KotlinFactory** [comment]
Hey Effendil,

I'm sorry I just saw this right now. 
As far as we know this was resolved already. Please tell me if I'm right.

To apply the fix, you need to put "zAdvanced.reload-data" to false.

Regards,
 Leonhard

**Comment by KotlinFactory** [comment]
Closed due to inactivity. Please comment if you want this reopened so we get notified.
