### ISSUE TITLE
Event EventLogin showing warn

### ISSUE THREAD

**Issue by ClassyTotodile** [Simplix-Softworks/PunishControl-Wiki#7]
**Describe the bug**
Whenever a player first join the server, the Event EventLogin will take longer than intended, causing a warning in console.

**Expected behavior**
The Event EventLogin should not have warnings whenever a player is joining the server.

**Screenshots**
Event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=LoginResult(id=6b1b39f8df92422d9251376e075b8314, name=RainbowDash__, properties=[LoginResult.Property(name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTYzMzc4OTQ2NzEyNiwKICAicHJvZmlsZUlkIiA6ICI2YjFiMzlmOGRmOTI0MjJkOTI1MTM3NmUwNzViODMxNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJSYWluYm93RGFzaF9fIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2MyYjU0ZWM2MWE0NmNmZDc0MzI1N2ZjNTk0NGJhMTVmOWQ3ZDE0YWMxODZkNmFjZjk5ZGZiOTZmMzU5M2Y0ZTYiCiAgICB9CiAgfQp9, signature=WF7LwPfSqDmmBhZQUjxnUqYca70s5Lt5YrbrzoZWaI+1fJL1guy2F3q3ieZ9gTdBwvV0vgFm7vZhGXC8/Aodguzr1d6XtgrF3mO4ROXUYpKSi8SmQzxc903PIVC2Hd5CDMp0XN/SMSzhVRj8WsmnExtke+ktHVrWjTLHqdIwhNAQmpQFbT7fZqhn50/q12VZ84n9g53dHLvJRNDnZKjq4MN6J2GbyIPEhU22c7NE9jSnznbvSqKGqlqmfn97KTZt/umuDuRKOEaK1BPNAOVQuCR5jJ50+3m3df+zHWKY6guToKiCbSFi3NRHqlbM8ZkVkWnHYTaFcgQmT4iSqusYYy7kJmK3OVVs8XtUb1dFW6bHPp9wP+G5h8Fxfd1s/+JgGlE1INl27wjjzB27cokBHcckF5dhiDTsxt1jNApLRHsOOQ6Co5HpR+EnqKcjJpSlRJhbE7TYkUIxrSU4JWxjBkMHOu/0PRL2el7MpCZMTd5slRdDDCEtTtuEMnEEWzp2OIti9BZ2L535Gw2kr8lJh7FsPXh2qSvPIYq3wMeRYf5QpmMxwRrElsoX/9NX/89CT05na+Fca5nbZJ0eJ599Utqc5CzormCpNMy1dY6vB7KLC/I22yF8hC8zA8OWhKYSBbbojh/BFjyC/V8YMlaVly4vFw1qivJA3ywJ2gjQoxg=)]), connection=[/73.36.184.143:63000|RainbowDash__] <-> InitialHandler) took 379ms to process!

**Platform**
- Which platform are you on: BungeeCord
- Which version is your server on: 1.17.1
- Are you using a fork: Waterfall 450

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 20.04
 - Java-Version: 16

**Files**
- [2021-10-09-7.log](https://github.com/Simplix-Softworks/PunishControl-Wiki/files/7315913/2021-10-09-7.log)

**To Reproduce**
If applicable:
1. Place PunishControl in the /plugins folder
2. Start the proxy
3. Restart the proxy
4. Have a new player join the server
5. Console should show the Event EventLogin warning

**Comment by KotlinFactory** [comment]
Hey ClassyTodile,

thank you so much for using PunishControl & reporting this.
This does not slow down the server at all - You can just ignore this.

However, we will have a look at this.

If you would like to receive real-time help feel free to join our Discord [here](https://discord.com/invite/CecJBxc)


Regards,
 Leonhard

**Comment by KotlinFactory** [comment]
Closed due to inactivity. Please comment if you want this reopened so we get notified.
